### ISSUE TITLE
Add models (User, Skyshot)

### ISSUE THREAD

**Issue by wmason1997** [steviesummers/simple-skies#7]
User {	
	_id:
	name:
	email:
	password:
	sky-shots: {
		[Skyshot]
	}
}

Skyshot {	
			city_input: (-> will be converted)
lat:
	lon:
date:
style:
searchQuery:
imageUrl: 
},

Just save the image URL to the database!

Save what the user searched as well

https://docs.google.com/document/d/1aTDFyoE2CyX2dQyfJyzJhi6vNjuXAOP2ojjhKCEVdrI/edit?usp=sharing

**Comment by steviesummers** [comment]
we did it
